package com.Patane.Brewery.Commands;

import com.Patane.Brewery.Commands.primary.createCommand;
import com.Patane.Brewery.Commands.primary.editCommand;
import com.Patane.Brewery.Commands.primary.giveCommand;
import com.Patane.Brewery.Commands.primary.helpCommand;
import com.Patane.Brewery.Commands.primary.infoCommand;
import com.Patane.Brewery.Commands.primary.listCommand;
import com.Patane.Brewery.Commands.primary.reloadCommand;
import com.Patane.Brewery.Commands.primary.removeCommand;
import com.Patane.Brewery.Commands.secondary.createEffect;
import com.Patane.Brewery.Commands.secondary.createItem;
import com.Patane.Brewery.Commands.secondary.infoEffect;
import com.Patane.Brewery.Commands.secondary.infoItem;
import com.Patane.Brewery.Commands.secondary.listEffects;
import com.Patane.Brewery.Commands.secondary.listItems;
import com.Patane.Brewery.Commands.secondary.removeEffect;
import com.Patane.Brewery.Commands.secondary.removeItem;
import com.Patane.Brewery.Commands.secondary.edit.editEffect;
import com.Patane.Brewery.Commands.secondary.edit.editItem;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectRemove;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectRemoveFilter;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectRemoveModifier;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectRemoveParticles;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectRemovePotions;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectRemoveRadius;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectRemoveSounds;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectRemoveTag;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectRemoveTrigger;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSet;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetFilter;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetFilterAdd;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetFilterRemove;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetIgnoreuser;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetModifier;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetParticles;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetPotions;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetPotionsAdd;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetPotionsRemove;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetRadius;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetSounds;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetTag;
import com.Patane.Brewery.Commands.secondary.edit.effect.editEffectSetTrigger;
import com.Patane.Brewery.Commands.secondary.edit.item.editItemCooldown;
import com.Patane.Brewery.Commands.secondary.edit.item.editItemEffects;
import com.Patane.Brewery.Commands.secondary.edit.item.editItemItemstack;
import com.Patane.Brewery.Commands.secondary.edit.item.editItemType;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsAdd;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModify;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifyRemove;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifyRemoveFilter;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifyRemoveModifier;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifyRemoveParticles;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifyRemovePotions;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifyRemoveRadius;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifyRemoveSounds;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifyRemoveTag;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifyRemoveTrigger;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySet;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetFilter;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetFilterAdd;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetFilterRemove;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetIgnoreuser;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetModifier;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetParticles;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetPotions;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetPotionsAdd;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetPotionsRemove;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetRadius;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetSounds;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetTag;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsModifySetTrigger;
import com.Patane.Brewery.Commands.secondary.edit.item.effects.editItemEffectsRemove;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackAttributes;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackAttributesAdd;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackAttributesRemove;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackEnchantments;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackEnchantmentsAdd;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackEnchantmentsRemove;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackFlags;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackFlagsAdd;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackFlagsRemove;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackLore;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackLoreDelete;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackLoreSet;
import com.Patane.Brewery.Commands.secondary.edit.item.itemstack.editItemItemstackName;
import com.Patane.Commands.CommandHandler;

public class BrCommandHandler extends CommandHandler{
	
	protected void registerAll() {
		// Primary commands
		register(reloadCommand.class);
		register(giveCommand.class);
		register(helpCommand.class);
		register(listCommand.class);
		register(infoCommand.class);
		register(createCommand.class);
		register(removeCommand.class);
		register(editCommand.class);
//		register(guiCommand.class);
		
		// Secondary commands
		register(listEffects.class);
		register(listItems.class);
		register(infoEffect.class);
		register(infoItem.class);
		register(createItem.class);
		register(removeItem.class);
		register(createEffect.class);
		register(removeEffect.class);
		
		register(editEffect.class);
		register(editEffectSet.class);
		register(editEffectSetModifier.class);
		register(editEffectSetTrigger.class);
		register(editEffectSetRadius.class);
		register(editEffectSetPotions.class);
		register(editEffectSetPotionsAdd.class);
		register(editEffectSetPotionsRemove.class);
		register(editEffectSetFilter.class);
		register(editEffectSetFilterAdd.class);
		register(editEffectSetFilterRemove.class);
		register(editEffectSetParticles.class);
		register(editEffectSetSounds.class);
		register(editEffectSetTag.class);
		register(editEffectSetIgnoreuser.class);
		register(editEffectRemove.class);
		register(editEffectRemoveModifier.class);
		register(editEffectRemoveTrigger.class);
		register(editEffectRemoveFilter.class);
		register(editEffectRemovePotions.class);
		register(editEffectRemoveParticles.class);
		register(editEffectRemoveSounds.class);
		register(editEffectRemoveRadius.class);
		register(editEffectRemoveTag.class);
		
		register(editItem.class);
		register(editItemCooldown.class);
		register(editItemType.class);
		register(editItemItemstack.class);
		register(editItemItemstackAttributes.class);
		register(editItemItemstackAttributesAdd.class);
		register(editItemItemstackAttributesRemove.class);
		register(editItemItemstackEnchantments.class);
		register(editItemItemstackEnchantmentsAdd.class);
		register(editItemItemstackEnchantmentsRemove.class);
		register(editItemItemstackFlags.class);
		register(editItemItemstackFlagsAdd.class);
		register(editItemItemstackFlagsRemove.class);
		register(editItemItemstackLore.class);
		register(editItemItemstackLoreSet.class);
		register(editItemItemstackLoreDelete.class);
		register(editItemItemstackName.class);
		
		register(editItemEffects.class);
		register(editItemEffectsAdd.class);
		register(editItemEffectsRemove.class);
		register(editItemEffectsModify.class);
		register(editItemEffectsModifySet.class);
		register(editItemEffectsModifySetModifier.class);
		register(editItemEffectsModifySetTrigger.class);
		register(editItemEffectsModifySetRadius.class);
		register(editItemEffectsModifySetFilter.class);
		register(editItemEffectsModifySetFilterAdd.class);
		register(editItemEffectsModifySetFilterRemove.class);
		register(editItemEffectsModifySetParticles.class);
		register(editItemEffectsModifySetSounds.class);
		register(editItemEffectsModifySetIgnoreuser.class);
		register(editItemEffectsModifySetTag.class);
		register(editItemEffectsModifySetPotions.class);
		register(editItemEffectsModifySetPotionsAdd.class);
		register(editItemEffectsModifySetPotionsRemove.class);
		register(editItemEffectsModifyRemove.class);
		register(editItemEffectsModifyRemoveTrigger.class);
		register(editItemEffectsModifyRemoveModifier.class);
		register(editItemEffectsModifyRemoveRadius.class);
		register(editItemEffectsModifyRemoveTag.class);
		register(editItemEffectsModifyRemoveFilter.class);
		register(editItemEffectsModifyRemovePotions.class);
		register(editItemEffectsModifyRemoveParticles.class);
		register(editItemEffectsModifyRemoveSounds.class);
		// Edit Item commands
		/*
		register(itemEditItem.class);
		register(itemEditItemName.class);
		register(itemEditItemLore.class);
		register(itemEditItemLoreSet.class);
		register(itemEditItemLoreDelete.class);
		register(itemEditItemFlags.class);
		register(itemEditItemFlagsAdd.class);
		register(itemEditItemFlagsRemove.class);
		register(itemEditItemEnchantment.class);
		register(itemEditItemEnchantmentAdd.class);
		register(itemEditItemEnchantmentRemove.class);
		register(itemEditItemAttributes.class);
		register(itemEditItemAttributesAdd.class);
		register(itemEditItemAttributesRemove.class);
		register(itemEditType.class);
		register(itemEditCooldown.class);
		register(itemEditEffects.class);
		register(itemEditEffectsAdd.class);
		register(itemEditEffectsRemove.class);
		register(itemEditEffectsEdit.class);
		register(itemEditEffectsEditSet.class);
		register(itemEditEffectsEditSetModifier.class);
		register(itemEditEffectsEditSetTrigger.class);
		register(itemEditEffectsEditSetRadius.class);
		register(itemEditEffectsEditSetFilter.class);
		register(itemEditEffectsEditSetFilterAdd.class);
		register(itemEditEffectsEditSetFilterRemove.class);
		register(itemEditEffectsEditSetParticles.class);
		register(itemEditEffectsEditSetSounds.class);
		register(itemEditEffectsEditSetTag.class);
		register(itemEditEffectsEditSetIgnoreUser.class);
		register(itemEditEffectsEditSetPotions.class);
		register(itemEditEffectsEditSetPotionsAdd.class);
		register(itemEditEffectsEditSetPotionsRemove.class);
		*/
	}
}
