main: com.Patane.Brewery.Brewery
version: ALPHA-6.0
name: Brewery
api-version: 1.14
commands:
  brewery:
    description: Primary Brewery command.
    aliases: [brew, br]
    usage: /brewery
depend: [ProtocolLib]